basic edit pass
waldekmastykarz/sp-dev-docs pull request #1
Opened 2016-11-29 01:58 UTC by davidchesnut

@waldekmastykarz great article! I'm submitting this PR with my edit pass. I will also add some comments to this PR about some of the changes I made. There were a couple sentences that were not working grammatically and I attempted to fix them. so please review and be sure the technical meaning still works for any changes I made. if good please merge back into your original PR #285. I will also have a few more review comments there that I'll add.

Thanks!

2016-11-29 06:38 UTC, waldekmastykarz commented on docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
> +When creating a custom property pane control that uses React in the SharePoint Framework, the web part consists of a class that registers the control with the web part, and a React component that ren
This is not quite correct. It's the custom property pane control not the web part that consists of a class that registers the control with the web part and a component for rendering the control.

2016-11-29 06:39 UTC, waldekmastykarz commented on docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
> +                Customize SharePoint experiences using web parts.
This is the standard string that is created by the SharePoint Framework Yeoman generator.

2016-11-29 06:42 UTC, waldekmastykarz commented on docs/spfx/web-parts/guidance/build-custom-property-pane-controls.md
> +The **AsyncDropdown** class represents the React component used to render the asynchronous dropdown property pane control. When the component first loads, the **componentDidMount** method, or its **d
Without parenthesis surrounding _the componentDidMount method_ the sentence seems confusing. It was meant as a pointer to the right fragment in code but if it obstructs reading then we could leave it out.

2016-11-29 06:50 UTC, waldekmastykarz requested changes
Hi David,

Thank you for your feedback and changes. They make it easier to read the article.
I've added a few comments regarding your changes. Could you please have a look at them?

Thank you,

Waldek

2016-11-29 17:09 UTC, davidchesnut commented
One of your comments at line 179 disappeared after I made a change to address it. Anyway the line now reads: When creating a custom property pane control that uses React in the SharePoint Framework, the control consists of a class that registers the control with the web part, and a React component that renders the dropdown and manages its data.

2016-11-29 17:10 UTC, davidchesnut commented
BTW: If there is a more efficient way to do these reviews I'm all ears. My first time trying this editing thing in GitHub. :-)

2016-11-30 04:56 UTC, waldekmastykarz commented
So is mine ;) Not sure if we're doing things correctly though so it might be that.

2016-11-30 04:57 UTC, merged

2016-11-30 04:59 UTC, waldekmastykarz commented
@davidchesnut PR is merged and directly pushed into my PR to the SharePoint repo. We can pick it up from there